theme: jekyll-theme-midnight
layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "resource/Siggraph2019"
    values:
      image: true

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Geometry Processing
    web_url: https://en.wikipedia.org/wiki/Geometry_processing
    image_url: assets/img/Polygon_Mesh_Processing_Book_Cover.jpg

  - name: Machine Learning
    web_url: https://en.wikipedia.org/wiki/Machine_learning
    image_url: assets/img/Kernel_Machine.svg.png

  - name: Compilers
    web_url: https://en.wikipedia.org/wiki/Compilers:_Principles,_Techniques,_and_Tools
    image_url: assets/img/Purple_dragon_book_b.jpg
